---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    standard: "PSR1,PSR2"
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/**/*
- "phpdoc.dist.xml"
